### ISSUE TITLE
introduce localization

### ISSUE THREAD

**Issue by SamuraiT** [henkaku-center/omise-interface#28]
Todo
- [x] decide translation strategy 
- [ ] introduce
- [ ] translate as community tasks

**Comment by SamuraiT** [comment]
Good ! wdyt about this ?
you can take either one 
https://nextjs.org/docs/advanced-features/i18n-routing

**Comment by geeknees** [comment]
My understanding is that it refers to what I am doing here.

https://github.com/henkaku-center/henkaku-discord-landing/blob/main/next.config.js

Roger that. I will take care of this.

**Comment by SamuraiT** [comment]
ok ! thanks

**Comment by alecrem** [comment]
So, I guess the l18n strategy is decided now. The same as the landing page sounds great.

Can I try to introduce it tomorrow?
