### ISSUE TITLE
without connecting wallet, badges page will return nothing

### ISSUE THREAD

**Issue by SamuraiT** [henkaku-center/omise-interface#92]
# problem 
- without connecting wallet, badges page will return nothing

# solution
- use RPC default provider to communicate
- or require connect wallet first

**Comment by alecrem** [comment]
This is still open after #93 (which looks like it should have closed this).

I checked that I do get the "connect wallet" button when not connected, so I can't reproduce the issue 👍

@SamuraiT I'll close the issue. Please reopen if I was wrong.
